version: '3.8'

services:
  # The Web API Service
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - db
      - redis

  # The Async Worker Service (consumes the queue)
  worker:
    build: .
    # Assuming you use Celery. If using Arq, change accordingly.
    command: celery -A src.worker.app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - db
      - redis

  # Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nexus

  # Message Broker
  redis:
    image: redis:7-alpine

  # MailHog - The "Senior" touch. 
  # Captures emails sent by the app so you can view them in a browser.
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

volumes:
  postgres_data:
